# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

# Site footer

footer:
  copyright:
    notice: "© {year} Silas Kieser. This work is licensed under {license}"
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ""
    org_name: ""
    description: "My personal webpage."
    twitter: "SilasKieser"
  analytics:
    google_analytics: "UA-111618908-1"
    baidu_tongji: ""
  verification:
    google: ""
    baidu: ""

# should go elsewhere

# Contact (edit or remove options as required)

# email: silas.kieser@gmail.com # was uncommented
# phone: 0041765007311
#address:
#  street: 1 Rue Michel Servet
#  city: Geneva
#  region: VD
#  postcode: '1211'
#  country: Switzerland
#  country_code: CH
#coordinates:
#  latitude: '46.193535'
#  longitude: '6.151304'
#directions: CMU - laboratory D06.1546.a
# office_hours:
#   - 'Monday 10:00 to 13:00'
#   - 'Wednesday 09:00 to 10:00'
# appointment_url: 'https://calendly.com'
# contact_links:
# - icon: twitter
#   icon_pack: fab
#   name: DM Me
#   link: 'https://twitter.com/SilasKieser'
# - icon: skype
#   icon_pack: fab
#   name: Skype Me
#   link: 'skype:echo123?call'
# - icon: keybase
#   icon_pack: fab
#   name: Chat on Keybase
#   link: 'https://keybase.io/'
# - icon: comments
#   icon_pack: fas
#   name: Discuss on Forum
#   link: 'https://discourse.gohugo.io'

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Localization
locale:
  date_format: "2. Jan 2006"
  time_format: "15:04"
  address_format: de

# Site features

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: "https://github.com/<username>/<repository>"
    content_dir: content
    branch: main
  avatar:
    gravatar: true
    shape: circle
  comment:
    provider: giscus
    disqus:
      shortname: ""
      show_count: true
    commento:
      url: ""
    giscus:
      repo: "silask/silask.github.io"
      repo_id: "MDEwOlJlcG9zaXRvcnkyODc3MjM3Nzc="
      #category: 'General'
      #category_id: 'DIC_kwDOESZRAc4CU7yv'
      category: "Announcements"
      category_id: "DIC_kwDOESZRAc4CU7yu"

  search:
    provider: wowchemy
    algolia:
      app_id: ""
      api_key: ""
      index_name: ""
      show_logo: false
  map:
    provider: ""
    api_key: ""
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
